### ISSUE TITLE
crashed decoder on Android 6.0

### ISSUE THREAD

**Issue by vitg8** [theeasiestway/android-opus-codec#10]
A/libc: invalid address or address of corrupt block 0x557a131c90 passed to dlfree

and 

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa1ff86ff6aff65 in tid 4654
 

am usage opus.aar

encoder very good

**Comment by theeasiestway** [comment]
@vitg8 Hi can you provide more details about the issue:
1. Is it stable?
2. Does it crash on encoding or on decoding or maybe in some another condition?

**Comment by vitg8** [comment]
> @vitg8 Hi can you provide more details about the issue:
> 
> 1. Is it stable?
> 2. Does it crash on encoding or on decoding or maybe in some another condition?

the problem is constant, even when I change the decoder parameters, I get a similar problem, I debug it on a real Asus z00ld android 6.0 device, on other devices this is not observed, respectively, the OS version is higher there

**Comment by theeasiestway** [comment]
@vitg8 Unfortunately I don't have any Asus devices to check this issue maybe if I get the device in several days I'll check the issue and try to fix it.
Can you also tell me the app crashes immediately when you press "PLAY" button or after few minutes?
Can you provide the whole logs after crash?

**Comment by vitg8** [comment]
> @vitg8 Unfortunately I don't have any Asus devices to check this issue maybe if I get the device in several days I'll check the issue and try to fix it.
> Can you also tell me the app crashes immediately when you press "PLAY" button or after few minutes?
> Can you provide the whole logs after crash?

crashes immediately when the decode () method is called; I have checked the parameters for errors several times already

maybe a problem in JNI type overflow or something like

checked by writing a small program in C#, the same data plays normally, I also used the native opus library

**Comment by theeasiestway** [comment]
@vitg8 yesterday I've checked the issue on the colleague's Asus Zenfone 2 android 6.0 and the app doesn't crash, unfortunately it was the only Asus that I could find to check the issue, maybe you can send more logs after crash the app I mean not only the one string but the full log?
