### ISSUE TITLE
Do I need to execute ndk-build command again ?

### ISSUE THREAD

**Issue by manishpatelgt** [theeasiestway/android-opus-codec#3]
If i move all the resources in one new project

**Comment by theeasiestway** [comment]
No you don't need it, everything you need already built and placed [here](https://github.com/theeasiestway/android-opus-codec/tree/develop/opus/src/main/cpp/lib) and [here](https://github.com/theeasiestway/android-opus-codec/tree/develop/opus/src/main/cpp/include).

**Comment by manishpatelgt** [comment]
@theeasiestway  Thanks for your quick replied
