### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by manishpatelgt** [theeasiestway/android-opus-codec#5]
I am getting error. I have added opus module in my project and other required files

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opus:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86_64/libopus.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
 
```

I have added files from your demo project

**app(level) -> jni
app(level) -> libs with all arms folders**

Any idea how to resolve ?

**Comment by theeasiestway** [comment]
If you want to use just Opus codec for encoding and decoding audio without editing a source code it'll be more easily to add the codec to your project as .aar library, more insctructions how to do it you can find in a readme:
https://github.com/theeasiestway/android-opus-codec/blob/develop/README.md#compiled-library

**Comment by manishpatelgt** [comment]
In that case i don't need to add any files under JNI, is that right ?

**Comment by manishpatelgt** [comment]
@theeasiestway  opus.aar worked very well. Thanks

**Comment by theeasiestway** [comment]
> In that case i don't need to add any files under JNI, is that right ? @theeasiestway

yes you don't need it
