### ISSUE TITLE
How to add this library for encoding and decoding in VOIP app of 325 bytes? How to use .aar and use to encode and decode? A full detailed tutorial or blog post please!

### ISSUE THREAD

**Issue by nafiskabbo** [theeasiestway/android-opus-codec#6]
How to add this library for encoding and decoding in VOIP app of 325 bytes? How to use .aar and use to encode and decode? A full detailed tutorial or blog post please! #6

**Comment by theeasiestway** [comment]
Hi @nafiskabbo I've already decscribed how to add the library to your project using gradle dependencies section [here](https://github.com/theeasiestway/android-opus-codec#compiled-library).
Also in the repository in the [app](https://github.com/theeasiestway/android-opus-codec/tree/develop/app) folder placed the source code of a sample android app that uses opus library and there you can find the code that makes encoding and decoding processes.
And [here](https://github.com/theeasiestway/android-opus-codec#how-to-use) I placed detailed instructions how to use the library.
